# see: https://github.com/OpenCatalogi/.github?tab=readme-ov-file
name: OpenCatalogi

on:
 workflow_dispatch:
 push:
  branches:
   - main
   - acceptance

permissions:
 contents: write



jobs:
 generatePublicCodeYaml:
  name: Generate Publiccode Yaml
  runs-on: ubuntu-latest
  steps:
   - name: Create or Update publiccode.yaml (acceptance)
     if: ${{ contains('acceptance', github.ref) }}
     uses: OpenCatalogi/publiccode-action@1.3.4
     with:
      federlize: false
      save: true
   - name: Create or Update publiccode.yaml (main)
     if: ${{ contains('main', github.ref) }}
     uses: OpenCatalogi/publiccode-action@1.3.4
     with:
      federlize: true
      save: false
